export const Users = [
  {
    id: 1,
    profilePicture: "assets/1714572224841.jpg",
    username: "Fahad Bin Qaiser",
  },
  {
    id: 2,
    profilePicture: "assets/profile-pic.png",
    username: "Faizan Bin Qaiser",
  },
  {
    id: 3,
    profilePicture: "assets/farig-log/pic1.jpg",
    username: "Alex Durden",
  },
  {
    id: 4,
    profilePicture: "assets/farig-log/pic2.jpg",
    username: "Dora Hawks",
  },
  {
    id: 5,
    profilePicture: "assets/farig-log/pic3.jpg",
    username: "Thomas Holden",
  },
  {
    id: 6,
    profilePicture: "assets/farig-log/pic4.jpg",
    username: "Shirley Beauchamp",
  },
  {
    id: 7,
    profilePicture: "assets/farig-log/pic5.jpg",
    username: "Travis Bennett",
  },
  {
    id: 8,
    profilePicture: "assets/farig-log/pic6.jpg",
    username: "Kristen Thomas",
  },
  {
    id: 9,
    profilePicture: "assets/farig-log/pic7.jpg",
    username: "Gary Duty",
  },
  {
    id: 10,
    profilePicture: "assets/farig-log/pic8.jpg",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/h2r.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 898,
    comment: 390,
  },
  {
    id: 2,
    photo: "assets/batmanwallpaper.jpg",
    desc: "Hey Paul!",
    date: "15 mins ago",
    userId: 2,
    like: 720,
    comment: 250,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/ghost.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/killjoy.png",
    desc:"Killjoy is the best. What do you think?",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/gta6.jpg",
    desc:"Most Hyped awaiting game.",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/amg.jpg",
    desc:"Specialize Your drive in a Mercedes amg.",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/bmw.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/landscape.jpg",
    desc:"There is nothing better than the beauty of nature.",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/suzuki.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/valo1.jpg",
    desc:"Play Valo With me.",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
